version: "3"
services:
  db:
    image: mysql:latest
    container_name: php_training_db
    environment:
        MYSQL_DATABASE: php_training
        MYSQL_USER: php_training
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
    ports:
        - "33306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
    tty: true

  php:
    build: ./docker/php
    container_name: php_training_app
    volumes:
      - ./docker/nginx/html:/usr/share/nginx/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./src:/var/www/html
    depends_on: 
      - "db"
    tty: true

  nginx:
    image: nginx:latest
    container_name: php_training_web
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/html:/usr/share/nginx/html
      - ./src:/app
    restart: always
    ports: 
      - "8080:80"
    depends_on: 
      - "php"
    tty: true